// <auto-generated />
using System;
using Lucky_Draw_Promotion.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Lucky_Draw_Promotion.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20220613081146_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Lucky_Draw_Promotion.Models.Admin", b =>
                {
                    b.Property<int>("AdminId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AdminId"), 1L, 1);

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordChangeString")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<byte[]>("PasswordSalt")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.HasKey("AdminId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Admins");

                    b.HasData(
                        new
                        {
                            AdminId = 1,
                            Email = "cooledm123@gmail.com",
                            FullName = "Nguyen Chinh Thi",
                            PasswordHash = new byte[] { 102, 80, 9, 246, 25, 19, 202, 254, 214, 181, 56, 222, 85, 48, 232, 14, 199, 147, 77, 64, 15, 214, 151, 237, 254, 185, 105, 207, 151, 93, 107, 74, 142, 167, 92, 109, 19, 115, 34, 253, 221, 125, 73, 150, 78, 4, 94, 96, 56, 76, 85, 87, 143, 171, 16, 21, 46, 34, 140, 168, 127, 65, 228, 51 },
                            PasswordSalt = new byte[] { 96, 140, 43, 70, 66, 220, 140, 56, 194, 61, 144, 155, 84, 136, 226, 120, 247, 34, 202, 202, 18, 99, 57, 150, 115, 8, 16, 209, 70, 86, 117, 187, 127, 164, 207, 151, 36, 168, 3, 20, 211, 16, 169, 97, 246, 152, 96, 61, 91, 57, 200, 35, 244, 144, 11, 85, 182, 84, 55, 80, 95, 0, 34, 139, 182, 16, 234, 239, 180, 134, 169, 61, 189, 66, 117, 177, 65, 50, 97, 187, 67, 133, 192, 21, 145, 108, 198, 64, 98, 27, 115, 25, 211, 248, 33, 92, 136, 135, 113, 29, 54, 123, 248, 24, 42, 127, 118, 184, 98, 125, 154, 34, 34, 126, 72, 164, 86, 180, 206, 5, 195, 194, 78, 116, 5, 253, 184, 157 }
                        });
                });

            modelBuilder.Entity("Lucky_Draw_Promotion.Models.Barcode", b =>
                {
                    b.Property<int>("BarcodeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BarcodeId"), 1L, 1);

                    b.Property<int>("Active")
                        .HasColumnType("int");

                    b.Property<string>("BarcodePic")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CampaignId")
                        .HasColumnType("int");

                    b.Property<int>("CodeCount")
                        .HasColumnType("int");

                    b.Property<int>("CodeLength")
                        .HasColumnType("int");

                    b.Property<int>("CodeRedemptionLimit")
                        .HasColumnType("int");

                    b.Property<int>("CreatedDate")
                        .HasColumnType("int");

                    b.Property<int>("ExpiredDate")
                        .HasColumnType("int");

                    b.Property<int>("Postfix")
                        .HasColumnType("int");

                    b.Property<int>("Prefix")
                        .HasColumnType("int");

                    b.Property<string>("QRCodePic")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Scanned")
                        .HasColumnType("int");

                    b.Property<int>("ScannedDate")
                        .HasColumnType("int");

                    b.Property<int>("Unlimited")
                        .HasColumnType("int");

                    b.Property<int>("UsedForSpin")
                        .HasColumnType("int");

                    b.HasKey("BarcodeId");

                    b.HasIndex("CampaignId");

                    b.ToTable("Barcodes");
                });

            modelBuilder.Entity("Lucky_Draw_Promotion.Models.Campaign", b =>
                {
                    b.Property<int>("CampaignId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CampaignId"), 1L, 1);

                    b.Property<int>("ApplyForAllCampaign")
                        .HasColumnType("int");

                    b.Property<int>("AutoUpdate")
                        .HasColumnType("int");

                    b.Property<string>("CampaignName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CharsetId")
                        .HasColumnType("int");

                    b.Property<int>("CodeCount")
                        .HasColumnType("int");

                    b.Property<int>("CodeLength")
                        .HasColumnType("int");

                    b.Property<int>("CodeUsageLimit")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Postfix")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Prefix")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProgramSizeId")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Unlimited")
                        .HasColumnType("int");

                    b.HasKey("CampaignId");

                    b.HasIndex("CharsetId");

                    b.HasIndex("ProgramSizeId");

                    b.ToTable("Campaigns");

                    b.HasData(
                        new
                        {
                            CampaignId = 1,
                            ApplyForAllCampaign = 1,
                            AutoUpdate = 1,
                            CampaignName = "Lucky Draw 1",
                            CharsetId = 1,
                            CodeCount = 1,
                            CodeLength = 10,
                            CodeUsageLimit = 1,
                            Description = "This is for test",
                            EndDate = new DateTime(2022, 6, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Prefix = "ALTA",
                            ProgramSizeId = 1,
                            StartDate = new DateTime(2022, 6, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Unlimited = 1
                        },
                        new
                        {
                            CampaignId = 2,
                            ApplyForAllCampaign = 2,
                            AutoUpdate = 1,
                            CampaignName = "Lucky Draw 2",
                            CharsetId = 1,
                            CodeCount = 1,
                            CodeLength = 10,
                            CodeUsageLimit = 1,
                            Description = "This is the second test",
                            EndDate = new DateTime(2022, 6, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Prefix = "ALTA",
                            ProgramSizeId = 2,
                            StartDate = new DateTime(2022, 6, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Unlimited = 1
                        });
                });

            modelBuilder.Entity("Lucky_Draw_Promotion.Models.Charset", b =>
                {
                    b.Property<int>("CharsetId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CharsetId"), 1L, 1);

                    b.Property<string>("CharsetName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CharsetValue")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CharsetId");

                    b.ToTable("Charsets");

                    b.HasData(
                        new
                        {
                            CharsetId = 1,
                            CharsetName = "Numbers",
                            CharsetValue = "123456789"
                        });
                });

            modelBuilder.Entity("Lucky_Draw_Promotion.Models.Customer", b =>
                {
                    b.Property<int>("CustomerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CustomerId"), 1L, 1);

                    b.Property<int>("Block")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("Fullname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PositionId")
                        .HasColumnType("int");

                    b.Property<int>("TOBId")
                        .HasColumnType("int");

                    b.HasKey("CustomerId");

                    b.HasIndex("PositionId");

                    b.HasIndex("TOBId");

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("Lucky_Draw_Promotion.Models.CustomerBarcode", b =>
                {
                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<int>("BarcodeId")
                        .HasColumnType("int");

                    b.HasKey("CustomerId", "BarcodeId");

                    b.HasIndex("BarcodeId");

                    b.ToTable("CustomerBarcodes");
                });

            modelBuilder.Entity("Lucky_Draw_Promotion.Models.Gift", b =>
                {
                    b.Property<int>("GiftId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("GiftId"), 1L, 1);

                    b.Property<int>("CampaignId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.HasKey("GiftId");

                    b.HasIndex("CampaignId");

                    b.HasIndex("ProductId");

                    b.ToTable("Gifts");
                });

            modelBuilder.Entity("Lucky_Draw_Promotion.Models.GiftCode", b =>
                {
                    b.Property<int>("GiftCodeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("GiftCodeId"), 1L, 1);

                    b.Property<int>("Active")
                        .HasColumnType("int");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("GiftId")
                        .HasColumnType("int");

                    b.HasKey("GiftCodeId");

                    b.HasIndex("GiftId");

                    b.ToTable("GiftCodes");
                });

            modelBuilder.Entity("Lucky_Draw_Promotion.Models.Position", b =>
                {
                    b.Property<int>("PositionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PositionId"), 1L, 1);

                    b.Property<string>("PositionName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PositionId");

                    b.ToTable("Positions");
                });

            modelBuilder.Entity("Lucky_Draw_Promotion.Models.Product", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductId"), 1L, 1);

                    b.Property<string>("ProductDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ProductId");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("Lucky_Draw_Promotion.Models.ProgramSize", b =>
                {
                    b.Property<int>("PSId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PSId"), 1L, 1);

                    b.Property<string>("PSDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PSName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PSId");

                    b.ToTable("ProgramSizes");

                    b.HasData(
                        new
                        {
                            PSId = 1,
                            PSDescription = "up to thousands of random discount codes designed for single use by a limited group customers (e.g., \"ACME - 5P13E\" gives $25 off for the first 3 purchases, new customers from Warsaw only).",
                            PSName = "Bulk codes"
                        },
                        new
                        {
                            PSId = 2,
                            PSDescription = "A fixed-code discount designed for multiple uses (e.g., 10% off with \"blackfriday\" code).",
                            PSName = "Standalone code"
                        });
                });

            modelBuilder.Entity("Lucky_Draw_Promotion.Models.TypeOfBusiness", b =>
                {
                    b.Property<int>("TOBId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TOBId"), 1L, 1);

                    b.Property<string>("TOBName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TOBId");

                    b.ToTable("TypeOfBusinesses");
                });

            modelBuilder.Entity("Lucky_Draw_Promotion.Models.Winner", b =>
                {
                    b.Property<int>("WinnerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("WinnerId"), 1L, 1);

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<int>("GiftCodeId")
                        .HasColumnType("int");

                    b.Property<int>("SendGift")
                        .HasColumnType("int");

                    b.Property<DateTime>("WinDate")
                        .HasColumnType("datetime2");

                    b.HasKey("WinnerId");

                    b.HasIndex("CustomerId");

                    b.HasIndex("GiftCodeId");

                    b.ToTable("Winners");
                });

            modelBuilder.Entity("Lucky_Draw_Promotion.Models.Barcode", b =>
                {
                    b.HasOne("Lucky_Draw_Promotion.Models.Campaign", "Campaign")
                        .WithMany("Barcodes")
                        .HasForeignKey("CampaignId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Campaign");
                });

            modelBuilder.Entity("Lucky_Draw_Promotion.Models.Campaign", b =>
                {
                    b.HasOne("Lucky_Draw_Promotion.Models.Charset", "Charset")
                        .WithMany("Campaigns")
                        .HasForeignKey("CharsetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Lucky_Draw_Promotion.Models.ProgramSize", "ProgramSize")
                        .WithMany("Campaigns")
                        .HasForeignKey("ProgramSizeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Charset");

                    b.Navigation("ProgramSize");
                });

            modelBuilder.Entity("Lucky_Draw_Promotion.Models.Customer", b =>
                {
                    b.HasOne("Lucky_Draw_Promotion.Models.Position", "Position")
                        .WithMany("Customers")
                        .HasForeignKey("PositionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Lucky_Draw_Promotion.Models.TypeOfBusiness", "TypeOfBusiness")
                        .WithMany("Customers")
                        .HasForeignKey("TOBId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Position");

                    b.Navigation("TypeOfBusiness");
                });

            modelBuilder.Entity("Lucky_Draw_Promotion.Models.CustomerBarcode", b =>
                {
                    b.HasOne("Lucky_Draw_Promotion.Models.Barcode", "Barcode")
                        .WithMany("CustomerBarcodes")
                        .HasForeignKey("BarcodeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Lucky_Draw_Promotion.Models.Customer", "Customer")
                        .WithMany("CustomerBarcodes")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Barcode");

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("Lucky_Draw_Promotion.Models.Gift", b =>
                {
                    b.HasOne("Lucky_Draw_Promotion.Models.Campaign", "Campaign")
                        .WithMany("Gifts")
                        .HasForeignKey("CampaignId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Lucky_Draw_Promotion.Models.Product", "Product")
                        .WithMany("Gifts")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Campaign");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Lucky_Draw_Promotion.Models.GiftCode", b =>
                {
                    b.HasOne("Lucky_Draw_Promotion.Models.Gift", "Gift")
                        .WithMany("GiftCodes")
                        .HasForeignKey("GiftId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Gift");
                });

            modelBuilder.Entity("Lucky_Draw_Promotion.Models.Winner", b =>
                {
                    b.HasOne("Lucky_Draw_Promotion.Models.Customer", "Customer")
                        .WithMany("Winners")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Lucky_Draw_Promotion.Models.GiftCode", "GiftCode")
                        .WithMany("Winners")
                        .HasForeignKey("GiftCodeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");

                    b.Navigation("GiftCode");
                });

            modelBuilder.Entity("Lucky_Draw_Promotion.Models.Barcode", b =>
                {
                    b.Navigation("CustomerBarcodes");
                });

            modelBuilder.Entity("Lucky_Draw_Promotion.Models.Campaign", b =>
                {
                    b.Navigation("Barcodes");

                    b.Navigation("Gifts");
                });

            modelBuilder.Entity("Lucky_Draw_Promotion.Models.Charset", b =>
                {
                    b.Navigation("Campaigns");
                });

            modelBuilder.Entity("Lucky_Draw_Promotion.Models.Customer", b =>
                {
                    b.Navigation("CustomerBarcodes");

                    b.Navigation("Winners");
                });

            modelBuilder.Entity("Lucky_Draw_Promotion.Models.Gift", b =>
                {
                    b.Navigation("GiftCodes");
                });

            modelBuilder.Entity("Lucky_Draw_Promotion.Models.GiftCode", b =>
                {
                    b.Navigation("Winners");
                });

            modelBuilder.Entity("Lucky_Draw_Promotion.Models.Position", b =>
                {
                    b.Navigation("Customers");
                });

            modelBuilder.Entity("Lucky_Draw_Promotion.Models.Product", b =>
                {
                    b.Navigation("Gifts");
                });

            modelBuilder.Entity("Lucky_Draw_Promotion.Models.ProgramSize", b =>
                {
                    b.Navigation("Campaigns");
                });

            modelBuilder.Entity("Lucky_Draw_Promotion.Models.TypeOfBusiness", b =>
                {
                    b.Navigation("Customers");
                });
#pragma warning restore 612, 618
        }
    }
}
